# Generated by Django 5.0.4 on 2024-05-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothcategory',
            options={},
        ),
    ]
