# Generated by Django 5.0.4 on 2024-05-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clothcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothcategory',
            options={'ordering': ('sort',)},
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('genre', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=50)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('purple', 'Purple'), ('brown', 'Brown'), ('orange', 'Orange'), ('gray', 'Gray'), ('beige', 'Beige')], max_length=50)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('material', models.CharField(choices=[('cotton', 'Cotton'), ('wool', 'Wool'), ('polyester', 'Polyester'), ('silk', 'Silk'), ('leather', 'Leather'), ('linen', 'Linen'), ('cashmere', 'Cashmere'), ('denim', 'Denim'), ('velvet', 'Velvet'), ('nylon', 'Nylon'), ('spandex', 'Spandex'), ('acrylic', 'Acrylic'), ('rayon', 'Rayon')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='cloth')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth', to='main.clothcategory')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
    ]
