# Generated by Django 5.0.4 on 2024-05-16 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+380509999999'. Up to 15 digits allowed.", regex='^\\+?38?\\d{9,15}$')]),
        ),
    ]
